### ISSUE TITLE
[next] System.onStart called multiple times

### ISSUE THREAD

**Issue by sh-dave** [PDeveloper/eskimo#10]
**https://github.com/sh-dave/eskimo-issues/tree/master/system-multiple-onStart**

Using systems with other-system-dependencies, depending on the order systems are added to the SystemManager, System.onStart() is called multiple times.

In this case, S2 depends on S1 and does a get in onStart();

``` haxe
class S2 extends System {
    var s1 : S1;

    public function new() super([S1]);

    override public function onStart( sm : SystemManager ) s1 = sm.get(S1);
}
```

``` haxe
sm.add(new S1());
sm.add(new S2());

will result in:

trace S1.onStart
trace S2.onStart
```

``` haxe
sm.add(new S2());
sm.add(new S1());

will result in:

trace S2.onStart
trace S1.onStart
trace S2.onStart
```

**Comment by PDeveloper** [comment]
Fixed on eskimo/next, good spot!
