### ISSUE TITLE
unable to use private-class components in views

### ISSUE THREAD

**Issue by sh-dave** [PDeveloper/eskimo#13]
```
private class Something {
    public var xxx: Int;
}

class SomeSystem extends System {
    var someView = new View<Something>();

    ...
}
```

Results in ```Type not found : Something``` in the ```someView = new View<>``` line.

**Comment by PDeveloper** [comment]
Is this working without Eskimo, and simply having a private class? I don't think Haxe supports "private" for classes.
http://try.haxe.org/#d8cC2

**Comment by sh-dave** [comment]
Eskimo issue, it's valid haxe code: https://haxe.org/manual/type-system-module-sub-types.html

**Comment by PDeveloper** [comment]
Yepz0rs, will check dis out!
