### ISSUE TITLE
removing components while iterating

### ISSUE THREAD

**Issue by sh-dave** [PDeveloper/eskimo#15]
What's the intended way of doing that?

```haxe
var objs = new View<A, B>();
... initialize objs with something...

for (e in objs.entities) {
   objs.manager.components.remove(e, A);
}
```

This won't work for all entities, as entities without A will be overwritten immediately.
- say we have these entities [0, 1, 2, 3]; Length 4 in objs, that all match
- the first iteration will remove A from 0;
- objs.entities will now contain [3, 1, 2, 3] / Length 3;
- next iteration, remove A from 1
- objs.entities will now container[3, 2, 2, 3] / Length 2;
- iteration will stop now

A workaround i found is using View.entities.entities
This will properly remove A from every entity, but it seems hard to remember.

```haxe
for (e in objs.entities.entities) {
   objs.manager.components.remove(e, A);
}
```

**Comment by sh-dave** [comment]
The workaround will also only work when you don't try to get components in the loop, or it will explode.

**Comment by PDeveloper** [comment]
Good catch! I'll have to be more clever about my custom iterator.

Another method of course is building up a list of entities that need A removed, and removing them afterwards, but yeah, I'll need to support this case.
