### ISSUE TITLE
[next] type arguments for views not working as expected

### ISSUE THREAD

**Issue by sh-dave** [PDeveloper/eskimo#8]
https://github.com/sh-dave/eskimo-issues

I put up a small repo in case there are more issues, so you can easily reproduce. :stuck_out_tongue: 
Just recursive clone and drop the issue folder into KS.

**https://github.com/sh-dave/eskimo-issues/tree/master/view-arguments**

`../s/S.hx:6: characters 18-26 : Type not found : c.C1`.

If you comment out the line, you see that this works for haxe's Map class.
It does also work when i put each component into it's own file and import them.

Edit: Also doesn't work when i try to import the actual class(es) by name:

```
import c.C.C1;
```

**Comment by PDeveloper** [comment]
Good catch!
Haven't tested these cases, but I'll have a go at getting this to work as soon as possible.

**Comment by PDeveloper** [comment]
You can just do:

```
import c.C;
```

and you should be able to use all contained types! Let me know if it works on your end.

**Comment by sh-dave** [comment]
:+1:
